# Generated by Django 4.2.8 on 2023-12-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalburgers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='side',
            field=models.ManyToManyField(blank=True, to='royalburgers.product'),
        ),
    ]
