# Generated by Django 4.2.8 on 2023-12-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalburgers', '0002_product_side'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='side',
            new_name='sides',
        ),
        migrations.AlterField(
            model_name='product',
            name='modifiers',
            field=models.ManyToManyField(blank=True, to='royalburgers.modifier'),
        ),
    ]
