# Generated by Django 4.2.8 on 2023-12-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalburgers', '0003_rename_side_product_sides_alter_product_modifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifier',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
