# Generated by Django 4.2.8 on 2023-12-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalburgers', '0004_alter_modifier_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifier',
            name='image',
            field=models.ImageField(upload_to='royalburgers/static/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='royalburgers/static/images/'),
        ),
    ]
