# Generated by Django 4.2.8 on 2023-12-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalburgers', '0005_alter_modifier_image_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifier',
            name='category',
        ),
        migrations.AddField(
            model_name='modifiercategory',
            name='modifiers',
            field=models.ManyToManyField(blank=True, to='royalburgers.modifier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modifiers',
            field=models.ManyToManyField(blank=True, to='royalburgers.modifiercategory'),
        ),
    ]
